DELETE FROM arcana;

INSERT INTO arcana (arcananame, arcananumber)
VALUES ('Fool', 0),
    ('Jester', 0),
    ('Magician', 1),
    ('Priestess', 2),
    ('Empress', 3),
    ('Emperor', 4),
    ('Hierophant', 5),
    ('Lovers', 6),
    ('Chariot', 7),
    ('Justice', 8),
    ('Hermit', 9),
    ('Fortune', 10),
    ('Strength', 11),
    ('Hanged Man', 12),
    ('Death', 13),
    ('Temperance', 14),
    ('Devil', 15),
    ('Tower', 16),
    ('Star', 17),
    ('Moon', 18),
    ('Sun', 19),
    ('Judgement', 20),
    ('Aeon', 20),
    ('World', 21);