DELETE FROM persona;

INSERT INTO persona(personaname, baselevel, arcananame)
VALUES ('Izanagi', 1, 'Fool'),
    ('Yomotsu-Shikome', 7, 'Fool'),
    ('Obariyon', 13, 'Fool'),
    ('Legion', 21, 'Fool'),
    ('Ose', 31, 'Fool'),
    ('Black Frost', 38, 'Fool'),
    ('Decarabia', 46, 'Fool'),
    ('Shiki-Ouji', 56, 'Fool'),
    ('Loki', 64, 'Fool'),
    ('Pixie', 2, 'Magician'),
    ('Orobas', 8, 'Magician'),
    ('Jack Frost', 16, 'Magician'),
    ('Hua Po', 25, 'Magician'),
    ('Pyro Jack', 32, 'Magician'),
    ('Dis', 39, 'Magician'),
    ('Rangda', 47, 'Magician'),
    ('Jinn', 62, 'Magician'),
    ('Surt', 69, 'Magician'),
    ('Mada', 78, 'Magician'),
    ('Saki Mitama', 11, 'Priestess'),
    ('Sarasvati', 17, 'Priestess'),
    ('High Pixie', 22, 'Priestess'),
    ('Ganga', 29, 'Priestess'),
    ('Parvati', 37, 'Priestess'),
    ('Kikuri-Hime', 48, 'Priestess'),
    ('Hariti', 59, 'Priestess'),
    ('Tzitzimitl', 70, 'Priestess'),
    ('Scathach', 79, 'Priestess'),
    ('Senri', 9, 'Empress'),
    ('Yaksini', 18, 'Empress'),
    ('Titania', 26, 'Empress'),
    ('Gorgon', 34, 'Empress'),
    ('Gabriel', 44, 'Empress'),
    ('Skadi', 52, 'Empress'),
    ('Mother Harlot', 60, 'Empress'),
    ('Alilat', 70, 'Empress'),
    ('Isis', 79, 'Empress'),
    ('Oberon', 12, 'Emperor'),
    ('King Frost', 22, 'Emperor'),
    ('Setanta', 34, 'Emperor'),
    ('Okuninushi', 41, 'Emperor'),
    ('Thoth', 45, 'Emperor'),
    ('Pabilsag', 51, 'Emperor'),
    ('Barong', 65, 'Emperor'),
    ('Odin', 74, 'Emperor'),
    ('Omoikane', 7, 'Hierophant'),
    ('Anzu', 15, 'Hierophant'),
    ('Shiisaa', 21, 'Hierophant'),
    ('Unicorn', 29, 'Hierophant'),
    ('Flauros', 36, 'Hierophant'),
    ('Hokuto Seikun', 45, 'Hierophant'),
    ('Cerberus', 52, 'Hierophant'),
    ('Daisoujou', 60, 'Hierophant'),
    ('Hachiman', 70, 'Hierophant'),
    ('Kohryu', 76, 'Hierophant'),
    ('Queen Mab', 25, 'Lovers'),
    ('Undine', 33, 'Lovers'),
    ('Leanan Sidhe', 42, 'Lovers'),
    ('Raphael', 53, 'Lovers'),
    ('Cybele', 64, 'Lovers'),
    ('Ishtar', 71, 'Lovers'),
    ('Slime', 2, 'Chariot'),
    ('Nata Taishi', 6, 'Chariot'),
    ('Eligor', 12, 'Chariot'),
    ('Ara Mitama', 18, 'Chariot'),
    ('Ares', 25, 'Chariot'),
    ('Triglav', 43, 'Chariot'),
    ('Kin-ki', 54, 'Chariot'),
    ('Thor', 65, 'Chariot'),
    ('Atavaka', 72, 'Chariot'),
    ('Futsunushi', 80, 'Chariot'),
    ('Angel', 4, 'Justice'),
    ('Archangel', 11, 'Justice'),
    ('Principality', 19, 'Justice'),
    ('Power', 27, 'Justice'),
    ('Virtue', 33, 'Justice'),
    ('Dominion', 38, 'Justice'),
    ('Throne', 49, 'Justice'),
    ('Uriel', 58, 'Justice'),
    ('Melchizedek', 66, 'Justice'),
    ('Sraosha', 74, 'Justice'),
    ('Forneus', 6, 'Hermit'),
    ('Ippon-Datara', 17, 'Hermit'),
    ('Lamia', 26, 'Hermit'),
    ('Mothman', 33, 'Hermit'),
    ('Hitokotonushi', 41, 'Hermit'),
    ('Kurama Tengu', 48, 'Hermit'),
    ('Nidhoggr', 55, 'Hermit'),
    ('Nebiros', 63, 'Hermit'),
    ('Arahabaki', 73, 'Hermit'),
    ('Ongyo-ki', 82, 'Hermit'),
    ('Fortuna', 35, 'Fortune'),
    ('Clotho', 44, 'Fortune'),
    ('Lachesis', 51, 'Fortune'),
    ('Ananta', 58, 'Fortune'),
    ('Atropos', 65, 'Fortune'),
    ('Norn', 72, 'Fortune'),
    ('Sandman', 5, 'Strength'),
    ('Valkyrie', 8, 'Strength'),
    ('Titan', 14, 'Strength'),
    ('Rakshasa', 23, 'Strength'),
    ('Kusi Mitama', 28, 'Strength'),
    ('Oni', 30, 'Strength'),
    ('Hanuman', 42, 'Strength'),
    ('Kali', 50, 'Strength'),
    ('Siegfried', 63, 'Strength'),
    ('Zaou-Gongen', 90, 'Strength'),
    ('Berith', 15, 'Hanged Man'),
    ('Yomotsu-Ikusa', 22, 'Hanged Man'),
    ('Makami', 27, 'Hanged Man'),
    ('Orthrus', 39, 'Hanged Man'),
    ('Yatsufusa', 49, 'Hanged Man'),
    ('Taowu', 56, 'Hanged Man'),
    ('Hell Biker', 66, 'Hanged Man'),
    ('Vasuki', 71, 'Hanged Man'),
    ('Attis', 82, 'Hanged Man'),
    ('Ghoul', 9, 'Death'),
    ('Mokoi', 14, 'Death'),
    ('Matador', 24, 'Death'),
    ('Samael', 36, 'Death'),
    ('Mot', 46, 'Death'),
    ('White Rider', 58, 'Death'),
    ('Alice', 72, 'Death'),
    ('Mahakala', 78, 'Death'),
    ('Apsaras', 4, 'Temperance'),
    ('Sylph', 11, 'Temperance'),
    ('Xiezhai', 16, 'Temperance'),
    ('Nigi Mitama', 23, 'Temperance'),
    ('Mithra', 31, 'Temperance'),
    ('Genbu', 40, 'Temperance'),
    ('Seiryuu', 47, 'Temperance'),
    ('Suzaku', 54, 'Temperance'),
    ('Byakko', 62, 'Temperance'),
    ('Yurlungur', 69, 'Temperance'),
    ('Vishnu', 73, 'Temperance'),
    ('Ukobach', 3, 'Devil'),
    ('Lilim', 10, 'Devil'),
    ('Vetala', 19, 'Devil'),
    ('Incubus', 28, 'Devil'),
    ('Pazuzu', 37, 'Devil'),
    ('Succubus', 44, 'Devil'),
    ('Lilith', 53, 'Devil'),
    ('Belphegor', 61, 'Devil'),
    ('Belial', 68, 'Devil'),
    ('Beelzebub', 81, 'Devil'),
    ('Taotie', 35, 'Tower'),
    ('Cu Chulainn', 46, 'Tower'),
    ('Abaddon', 55, 'Tower'),
    ('Mara', 62, 'Tower'),
    ('Masakado', 69, 'Tower'),
    ('Yoshitsune', 75, 'Tower'),
    ('Shiva', 80, 'Tower'),
    ('Kaiwan', 24, 'Star'),
    ('Neko Shogun', 32, 'Star'),
    ('Fuu-ki', 43, 'Star'),
    ('Ganesha', 50, 'Star'),
    ('Garuda', 57, 'Star'),
    ('Kartikeya', 67, 'Star'),
    ('Saturnus', 75, 'Star'),
    ('Helel', 87, 'Star'),
    ('Andras', 20, 'Moon'),
    ('Nozuchi', 27, 'Moon'),
    ('Yamata-no-Orochi', 34, 'Moon'),
    ('Alraune', 41, 'Moon'),
    ('Girimehkala', 48, 'Moon'),
    ('Sui-ki', 57, 'Moon'),
    ('Seth', 68, 'Moon'),
    ('Baal Zebul', 77, 'Moon'),
    ('Sandalphon', 84, 'Moon'),
    ('Cu Sith', 10, 'Sun'),
    ('Feng Huang', 20, 'Sun'),
    ('Gdon', 31, 'Sun'),
    ('Yatagarasu', 40, 'Sun'),
    ('Narasimha', 47, 'Sun'),
    ('Tam Lin', 53, 'Sun'),
    ('Jatayu', 61, 'Sun'),
    ('Horus', 68, 'Sun'),
    ('Suparna', 77, 'Sun'),
    ('Asura', 86, 'Sun'),
    ('Gurr', 20, 'Jester'),
    ('Take-Minakata', 27, 'Jester'),
    ('Pale Rider', 34, 'Jester'),
    ('Loa', 40, 'Jester'),
    ('Baphomet', 47, 'Jester'),
    ('Kumbhanda', 55, 'Jester'),
    ('Chernobog', 62, 'Jester'),
    ('Seiten Taisei', 68, 'Jester'),
    ('Magatsu-Izanagi', 77, 'Jester'),
    ('Ame-no-Uzume', 18, 'Aeon'),
    ('Narcissus', 24, 'Aeon'),
    ('Sati', 31, 'Aeon'),
    ('Raja Naga', 37, 'Aeon'),
    ('Kushinada-Hime', 44, 'Aeon'),
    ('Quetzalcoatl', 51, 'Aeon'),
    ('Kingu', 58, 'Aeon'),
    ('Lakshmi', 65, 'Aeon'),
    ('Kaguya', 74, 'Aeon'),
    ('Anubis', 59, 'Judgement'),
    ('Trumpeter', 67, 'Judgement'),
    ('Michael', 72, 'Judgement'),
    ('Satan', 76, 'Judgement'),
    ('Metatron', 83, 'Judgement'),
    ('Ardha', 90, 'Judgement'),
    ('Lucifer', 93, 'Judgement'),
    ('Izanagi-no-Ookami', 91, 'World');

SELECT * FROM persona;